# Generated by Django 5.2 on 2025-04-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
